### ISSUE TITLE
[ISSUE] - Can't start Anyshortcut on unloaded page

### ISSUE THREAD

**Issue by francis-du** [anyshortcut/anyshortcut#1]
Can't start Anyshortcut on unloaded page
![image](https://user-images.githubusercontent.com/25944814/72119003-f0b4af80-338d-11ea-9e0c-de74f269ea8d.png)

**Comment by Folyd** [comment]
@francis-du  Thanks for reporting. This is a known issue as is due to the Chrome extension API limitation, which doesn't allow the scripts injection to some special pages.  

Those special pages include and not limited to:
- Chrome Webstore page
- uploaded pages
- chrome:// pages

**Comment by francis-du** [comment]
@Folyd  Got it,thanks for your reply
